### ISSUE TITLE
2023-10-03 - Oversight Committee Agenda

### ISSUE THREAD

**Issue by seanmcilroy29** [Green-Software-Foundation/oc#52]
## Agenda - 2023-10-03

Time 15:30 (UTC) - See the time in your [timezone](https://everytimezone.com/s/5c485561)

- Chair – Tammy McClellan (Microsoft)  
- Vice-Chair – Chris Lloyd-Jones (Avanade)
- Convener – Russ Trow (GSF)

## Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

## Roll Call
Please add 'Attended' to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:

## Agenda
- [ ] Review/Approve agenda

## OC Governance Model
* Build a shared understanding of the purpose of the GSF OC
* [Oversight Committee Documentation](https://oc.greensoftware.foundation/)
* Start with the Responsibilities & Project Lifecycle

- [x] Review the [OC responsibilities](https://oc.greensoftware.foundation/oc-responsibilities.html)
- [x] Review the [Project Lifecycle](https://oc.greensoftware.foundation/project-lifecycle.html)

## Project Graduation
- [x] (re)Start the graduation process for [Carbon Aware SDK v1](https://github.com/Green-Software-Foundation/carbon-aware-sdk)
  - [ ] https://github.com/Green-Software-Foundation/oc/issues/23

## Governance
- [ ] https://github.com/Green-Software-Foundation/oc/issues/49
- [ ] https://github.com/Green-Software-Foundation/oc/issues/26
- [ ] Green-Software-Foundation/oc#50 

## AOB
- [ ] Any questions or other business

## Next meeting
- [ ] 07th November 2023

## Adjourn
- [ ] Any objections?

**Comment by russelltrow** [comment]
[Oversight Committee pack for October 2023](https://github.com/Green-Software-Foundation/oc/files/12781700/Oversight.Committee.-.October.2023.pdf)

**Comment by adamj89** [comment]
Attended

**Comment by Henry-WattTime** [comment]
Attended

**Comment by srini1978** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by russelltrow** [comment]
# Meeting Notes

## OC Governance

### [Responsibilities](https://oc.greensoftware.foundation/oc-responsibilities.html)

* Only a limited number of attendees were aware of the existing documentation or responsibilities.
* Agreed to review and propose changes through Pull Requests to the [OC repository](https://github.com/Green-Software-Foundation/oc)
* The following changes were suggested:
  * Improve the navigation by introducing a hierachy
  * Amend the 2nd responsibility to cover "reviewing" rather than "approving" projects
  * Amend the 3rd responsibility dropping “for releases” and replacing with “when not covered by WG practises”
* PRs would be raised to enact the suggested changes.
* The group then expressed it's approval of the responsibilities accepting the changes noted above.

### [Lifecycle](https://oc.greensoftware.foundation/project-lifecycle.html)

* The group reviewed the lifecycle and expressed it's approval of the current process as documented
* The following questions were raised:
  * Are there timescales for each stage?
    * The group didn't believe there should be timescales associated with stages but all projects should be periodically reviewed to ensure they are active
  * How do we handle different types of projects?
    * To be discussed further. Start by working with well defined Open Source Software projects before exploring other types such as Specifications (e.g. SCI)

### [Governance](https://oc.greensoftware.foundation/oc-governance.html)

* The group reviewed the rules and suggested the following changes:
  * In point 1 replace “Project Leads of graduated projects” with “Project Leads of active projects” 
* It was discussed that this connects to the previously raised PR https://github.com/Green-Software-Foundation/oc/pull/48
* PR would be raised to enact the suggested changes.
* The group then expressed it's approval of the rules

## Graduation of the Carbon Aware SDK v1 (CASDK)

* The group discussed the Project Lifecycle in relation to the CASDK, especially the [incubation exit criteria](https://oc.greensoftware.foundation/project-incubation-exit.html).
* It was unclear who should be responsible for completing the checklist, is this the responsibility of the OC or the Project Lead?
  * The current understanding is that the Project Lead should demonstrate to the OC that the project meets the criteria
* @Henry-WattTime proposed that rather than reviewing the currently stated exit criteria the group identify what it really means for a project to be graduated. It was agreed that issue #23 would be used to gather feedback from the wider OC.
  * Feedback will be discussed in the next OC meeting

## [[Agenda Item] Non-member participation](https://github.com/Green-Software-Foundation/oc/issues/35)

* The abilities of non-members to contribute to projects was discussed
* The idea of an "observer" status was raised allowing contributions to GitHub and attendance of project calls
* An informal recommendation will be made to the Steering Committee to broaden the definition of ICs
* #35 will be updated accordingly

## Actions

- [ ] @seanmcilroy29 review the Zoom meeting setup to ensure the meeting doesn't close unexpectedly 
- [ ] Raise a PR for changes to the OC documentation navigation
- [ ] @Henry-WattTime raise a PR for changes to the OC responsibilities documentation
- [ ] Raise a PR for changes to the OC governance documentation
- [ ] @russelltrow clarify responsibilities in regards to the incubation exit checklist
